# Generated by Django 5.0.4 on 2024-05-25 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField()),
                ('has_been_seen', models.BooleanField(default=False)),
                ('from_who', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='from_who', to=settings.AUTH_USER_MODEL)),
                ('to_who', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='to_who', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
